[package]
name = "toktok-py"
description = "Python bindings for toktok"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "_toktok"
crate-type = ["cdylib"]
test = false
doctest = false
path = "src/lib.rs"

[dependencies]
pyo3 = { version = "0.29.2", features = ["extension-module", "abi3-py311"] }
toktok-rs = { path = "../toktok" }
